### ISSUE TITLE
Debug data  - does it affect performance? some numbers show differently on Pinecil Debug

### ISSUE THREAD

**Issue by River-Mochi** [builder555/PineSAM#107]
**Is your feature request related to a problem? Please describe.**

Some numbers show differently inside Pinecil Debug versus what is displayed on pineSAM  debug list:

1. On the actual Pinecil  in Debug menu  the handle temperature shows correctly

Han C  = 27.5   Celsius
![IMG-3660](https://user-images.githubusercontent.com/97197236/224917484-bbcf0d5f-9d6e-4407-8b8d-fd2279598e18.jpg)

In the Debug  data section of PineSAM  it shows as the 275
![image](https://user-images.githubusercontent.com/97197236/224917333-78502bbc-3365-45d5-b4fa-64349dc82a6f.png)

Is Pinecil just sending the raw information without  divide by 10?  yet on the pinecil itself is doing the calculation and displaying it correctly with decimal?

2. Same with Input voltage,  I have 27.9V  and the debug data shows it as 279  without the decimal.

3.  if some data is already shown other places such as Input voltage , is it needed to have that in Debug info?  meaning is it taking more resources to poll this from  Pinecil?

4. do we only poll  pinecil and affect BLE performance  only if the "Debug category" is expanded or it's always going to  be same, for example movement data.  I'm only concerned if any of this  is going to affect performance on pinecil or strange behavior,  and then of course preference is not to have it.

**Comment by builder555** [comment]
1,2: the reason I am displaying raw values is to be able to debug the app as well, in case some divisions are happening incorrectly.

3,4: I am using bulk data feature, so it does not put any more stress on ble or cpu than displaying the current temperature alone.
