### ISSUE TITLE
bug: QC voltage range on Box change doesn't allow using 9-22 numbers or decimals

### ISSUE THREAD

**Issue by River-Mochi** [builder555/PineSAM#112]
**To Reproduce**
Steps to reproduce the behaviour:
1.  attempt to change QC voltage to 11.8 using the Box.
2. Error message appears  that I'm not in the allowed range.
3. the slider is working, but the Box does not. if I type 12 enter it gives me an error, it wants 120 for 12. For 11.8 I have to type 118. it doesn't like the decimal point and it thinks the range is 90-220.

**Expected behaviour**

- that it allows the correct  range of 9V - 22V  with decimals  that IronOS supports on the pinecil screen (i.e. 11.7 or 11.8). 
- I can change it inside Pinecil, and refresh browser and it shows correctly if I enter 11.8v or 12v  on Pinecil then refresh browser which then shows it correctly.
- but if I try to make any change on PineSAM box by typing, it Errors and wants 90-220 which doesn't exist for QC.
- I have some QC3.0 chargers and like to preset the QC setting to 12V permanently to be ready for when I plug into those. Right now I can only do it on Pinecil directly or using  the slider seems to work.

**Screenshots**
![image](https://user-images.githubusercontent.com/97197236/225224070-33410ba0-bb47-493b-8c2a-263e4efb6977.png)

**Specs:**
 - OS: [e.g. Windows 11]
 - Browser: chrome
 - PineSAM Version: 1.11.1
 - IronOS build: 2.20 BLE beta
 
 Side note:   IronOS does not support QC2.0. 
 Reason Ralim allows up to 22V here is for experimenting since it's an odd number.
<img src="https://user-images.githubusercontent.com/97197236/225235715-939b9c57-6297-4054-bde8-58baee2c884b.png" width ="450">

**Comment by builder555** [comment]
that is the value that IronOS expects, it's done in order to avoid decimals. When entering values manually, you enter the raw values.
