### ISSUE TITLE
consider adding Topics to repo

### ISSUE THREAD

**Issue by River-Mochi** [builder555/PineSAM#113]
- Adding Topics to repo help people find it easier
- Suggested topics: **pine64, pinecil, soldering, soldering-irons, bluetooth, BLE**
- Click on Gear icon to start.
- Github will also suggest topics to the owner that can be accepted or rejected.
- Reference:  https://backrightup.com/blog/how-to-organize-github-repositories/

Example of a related topics section:
![image](https://user-images.githubusercontent.com/97197236/225244677-3d9348ec-d63e-4780-90dc-e0a940350ea9.png)

**Comment by builder555** [comment]
done. thank you for the suggestion.
