### ISSUE TITLE
emotes for Issue tickets to make it more fun

### ISSUE THREAD

**Issue by River-Mochi** [builder555/PineSAM#114]
for issue tickets,  suggest adding a github emote before each category:

My suggestions

🐛 `:bug:`  for bug reports
 🚀 `:rocket:`     feature request 
📑 `:bookmark_tabs:`   to report issue with documentation
❓  `:question:`  for general questions Something else
👺   `:japanese_goblin`   security vulnerability  report

reference: https://github-emoji-picker.vercel.app/

Example of what one looks like with emotes:
![image](https://user-images.githubusercontent.com/97197236/225268891-9fae93df-9667-40da-a42d-a3a11bfa3daf.png)

**Comment by builder555** [comment]
if i make it more fun, people will create more tickets. i don't want more tickets 😆
