### ISSUE TITLE
add font awesome to repo 

### ISSUE THREAD

**Issue by River-Mochi** [builder555/PineSAM#115]
add font awesome to repo so we can use the free font awesome symbols in the wiki and documentation.
it might just need a couple lines of this code and it's done (unsure of how easy they make it sound).

https://gkoberger.github.io/Font-Awesome/get-started/

reference repo:  https://github.com/FortAwesome/Font-Awesome

**Comment by builder555** [comment]
Can't be done: https://stackoverflow.com/questions/51956361/custom-css-file-for-readme-md-in-a-github-repo/51956450#51956450
