### ISSUE TITLE
Stop using external resources

### ISSUE THREAD

**Issue by MagicLike** [builder555/PineSAM#125]
**Is your feature request related to a problem? Please describe.**
Especially Google and Cloudflare are absolutely privacy invasive.
Cloudflare can among other things:

- inject / modify JS (into the website)
- spy on you and the page's users
- track users across websites 

Google (and Google Fonts in this case) tracks users across pages and spies on what they are doing too. Also Google Fonts is - to my knowledge - illegal to use in the EU, due to the GDPR. 

**Describe the solution you'd like**
Please host such external resources - like CSS and fonts - locally, rather than calling them every time.
Another option for Google Fonts would be to use [Bunny Fonts](https://fonts.bunny.net).

**Additional context**
![External resources called by PISAM](https://user-images.githubusercontent.com/82117109/227785935-c4cc076f-a30d-454e-a85a-8fbf2cc42a7f.png)

**Comment by builder555** [comment]
@MagicLike is using google fonts illegal only when they're hosted on google's CDN or even locally-hosted?

**Comment by MagicLike** [comment]
> @MagicLike is using google fonts illegal only when they're hosted on google's CDN or even locally-hosted?

Nope, as if you are "hosting Google Fonts locally" you are only hosting the font files and the license (typically something like OFL.txt), so you can't really call it hosting Google Fonts... ^^

**Comment by MagicLike** [comment]
Thank you!
