### ISSUE TITLE
esbuild.exe  access  denied  windows11

### ISSUE THREAD

**Issue by River-Mochi** [builder555/PineSAM#134]
**To Reproduce**
Steps to reproduce the behaviour:

install pinesam Source-all v 1.12.8   or 1.12.9  on windows11
using setup-dev.bat   in Powershell.

**1.  "access denied" to esbuild**
`node_modules\@esbuild\win32-x64\esbuild.exe - Access is denied.`

![image](https://user-images.githubusercontent.com/97197236/227848415-05f978d1-708f-4410-a4b6-678c5f86b85e.png)

There might be a solution  for Windows and   **access denied to esbuild.exe** 

1. at  this page https://github.com/evanw/esbuild/issues/369

2. ![image](https://user-images.githubusercontent.com/97197236/227849705-755cf9e4-4b5d-4893-96a7-97759bdc73a1.png)

3. and at bottom of this page:
https://elixirforum.com/t/cant-execute-esbuild-permission-denied-on-windows-10/42271/8

**Comment by builder555** [comment]
this has been fixed by the upstream package
