### ISSUE TITLE
Sourcemap error message  when running .bat file  in Windows11

### ISSUE THREAD

**Issue by River-Mochi** [builder555/PineSAM#135]
I decided to separate out all the windows error messages from setup-dev.BAT  since they are solved differently. 

**To Reproduce**
Steps to reproduce the behaviour:
 Terminal Powershell, using  Source-all build,  all  versions get this error message

- For the Sourcemap  error message,  requesting to change to newer version in my, I found this.  perhaps this could help if PineSAM switched to this one in the code?  
this is NPM.

- NPM announces to everyone to stop using the  old  sourcemap 
https://www.npmjs.com/package/sourcemap-codec

- this is the new one:  https://www.npmjs.com/package/@jridgewell/sourcemap-codec
- it's the same command  to install this one too.

**Comment by builder555** [comment]
It's a warning, comes from one of the upstream packages, sourcemap-codec isn't used in pinesam directly.
