### ISSUE TITLE
Improve install instructions

### ISSUE THREAD

**Issue by Spagett1** [builder555/PineSAM#136]
Gday, 
I just installed this on my laptop and after running the start.sh script i didn't realise i needed to open up localhost:8080 in a browser. Just adding a single line saying "you can open pinesam at localhost:8080" or something like that.

This is mentioned in the dev section

```
Some Linux distros may need http://localhost:8080 opened manually. 
``` 
Just copy pasting this into the install section would be great.

Thanks for making such a cool project!

**Comment by River-Mochi** [comment]
I will replicate that important  info for each set of instructions so if people only  zoom into the Dev install or zoom into the pre-made binary , it will be clear so  they are not scratching their head for 10 min on what to do  ;)

**Comment by Spagett1** [comment]
Cheers haha, also it may be possible to auto open the browser on linux via the xdg-open command. It still wouldn't work on absolutely every distro but it would work on much more as it is the standard command for that function.

Something like:
```
if macos {
    open "url"
} else {
    xdg-open "url" 
} 
```
Later i can test this out and maybe make a merge request.

**Comment by River-Mochi** [comment]
Please close this ticket as it was  fixed  this morning with the Pull release  :)

**Comment by Spagett1** [comment]
Will do
