### ISSUE TITLE
Add version number, and Icon with  link to Github PineSAM

### ISSUE THREAD

**Issue by River-b** [builder555/PineSAM#14]
1. Suggestion to have a version number for PineSAM  that shows in tiny font at top left and make "Pinecil V2 Settings and Menu" a lot smaller font and possibly just move it down to next line

### PineSAM     (PineSAM  can be same bold)
v 1.00 13-02-2023   (version number/date in very small, non bold font)

![image](https://user-images.githubusercontent.com/97197236/219981675-aabedfbb-3c75-4565-99f0-21218f4e3e9d.png)

2. PineSAM - Pinecil V2 Settings and Menus  makes top  a little busy.   just PineSAM alone by itself would be fine :)  don't need the "Pinecil V2 Settings And Menus " as people can get that inside the readme.  keeps app cleaner less clutter to distract from functions .  however having a version number is good for communication so you know if people are using the newest app or an old one.
3. Could add a Github cat  to the corner like in Joric's BLE.  that github cat  is animated and if you hover over it, it waves. if you click the cat,  it opens link to the Github Dev.  
 Would be very nice and convenient to have same on PineSAM  so  users can get back to main repo fast to check for updates and  read notes also if there is an issue , and to open issue ticket.
I don't know where Joric got the Github Cat icon, but when you hover over it,  the cat waves at you to indicate it does  something.
This also makes screen  clean and not cluttered  with long link name to get to the Github.

![image](https://user-images.githubusercontent.com/97197236/219982309-b808e871-9290-40d9-9fbb-1b1803cff0d8.png)

**Comment by River-b** [comment]
In the Readme page also. I'm not sure when I click on Windows download which zip it is and if it's a new version or same old one.  only way to know is to try it and see if I see changes. 

if there is a way to name the link with version number or something so that people know it's a newer one than they downloaded last week or something.   this is minor but good to know for future :)

**Comment by builder555** [comment]
good suggestions about the font/version tweaks, i can work on that.
i can probably just copy the cat from Joric's page, unless he paid for it.

the link to the zip file is always the latest, it's the same as clicking CODE > DOWNLOAD 

the version thing is a bit more tricky to get right. i was actually looking into it already, just need to set it up to update automatically without having to remember, otherwise there'll be even more confusion.

**Comment by River-b** [comment]
https://tholman.com/github-corners/

**Comment by builder555** [comment]
ahhh, looks like adding automatic version numbers also created releases. can't be bothered today to figure out how to hide those, let's see if people start complaining 🤷

**Comment by River-b** [comment]
> ahhh, looks like adding automatic version numbers also created releases. can't be bothered today to figure out how to hide those, let's see if people start complaining 🤷

you have a Release Zip now :)     Grats on your first release.   you think that will lead to complaints?

**Comment by River-b** [comment]
is it possible to  Zip the README   with the Zip  so there is an instruction text with it? that might help

**Comment by builder555** [comment]
>you mean complaints because they grab the release zip but then don't know what to do because they skip Readme?
yup

> is it possible to Zip the README with the Zip so there is an instruction text with it? that might help

it's already there. hopefully people read it :)

**Comment by River-b** [comment]
Closing ticket as completed.
version number works and Github cat works to redirect to PineSAM project.
![image](https://user-images.githubusercontent.com/97197236/220182581-0b3b9bbd-be87-43a9-b5d9-3d4b9f1dd9f9.png)
