### ISSUE TITLE
Windows binary version script has  error with Wait-Process

### ISSUE THREAD

**Issue by River-Mochi** [builder555/PineSAM#148]
**To Reproduce**
Steps to reproduce the behaviour:
1. use  start.ps1  powershell terminal script
2.  problem with  $LASTEXITCODE   it does not get any  process ID for the Wait-process to work properly 

**Expected behaviour**
no error messages and the Wait happens.

**Actual behaviour**
pinesam seems to work even with this error, but it would be nice to fix the script of  Start.ps1
right now the Wait-Process fails and the script sends you back to command line.
I tested it and  $LASTEXITCODE and  $pid1 and $pid2 are empty. 

I'm testing some fixes now for this script and I think I have it fixed but  would  like advice on it since it could maybe be better. 

**Screenshots**
![Windows binary error wait-process](https://user-images.githubusercontent.com/97197236/229108183-fe55e6fd-e60f-4519-9919-48396b95a6e3.png)

**Specs:**
 - OS: [Windows 11
 - Browser: [e.g. chrome,
 - PineSAM Version: [e.g. 1.12.11  also happens on older versions
 - IronOS build: [e.g. 2.20. newest beta 128 uuid  but also happens on older versions

**Comment by River-Mochi** [comment]
@StevenSeifried  could you try this alternate start.ps1   in Windows. 

-    it has some extra  code in it that also  shows what  your actual Process ID's are .
-  double check with Ctrl+Alt+delete  task manager that the Process ID's match for  main_server and server

[start.zip](https://github.com/builder555/PineSAM/files/11124316/start.zip)

**Comment by StevenSeifried** [comment]
Your script works fine. PID's are the same as in task manager

**Comment by River-Mochi** [comment]
I submitted  PR to fix this.  new script gets the real process ID  and  the Wait-process works.

**Comment by River-Mochi** [comment]
closed per PR fix.
