### ISSUE TITLE
name  Ubunto  premade binary into  Linux

### ISSUE THREAD

**Issue by River-Mochi** [builder555/PineSAM#161]
is it possible  to name the  premade binary "Ubunto" package  into Linux? it would help  the document references be more consistent since we never say download the Ubunto package, we say  Linux.

PineSAM-Ubunto-x64-v1.12.14.zip   ===>  PineSAM-Linux-x64-v1.12.14.zip

**Comment by builder555** [comment]
Linux is a very generic name, there are 100s of flavours, and this binary likely won't run on distros that are not debian-based, naming it "linux" will create a lot more confusion than referring to it as "linux" in the documentation. Any linux user will know that Ubuntu is a linux distro.
