### ISSUE TITLE
BLE unique name is gone

### ISSUE THREAD

**Issue by River-Mochi** [builder555/PineSAM#166]
**To Reproduce**

Is BLE unique name gone for IronOS 2.21?  Tom said he also sees the  Unique name is gone. 
 **See screenshot**

**Expected behaviour**
it used to show BLE unique name-number
Will  BLE MAC  Address be used now for unique name?  will this be issue for MacOS?

**Screenshots**
![image](https://user-images.githubusercontent.com/97197236/230593330-5812852e-b799-4f63-a74b-64f4f9462fd7.png)

**Specs:**
 - OS: [e.g. Windows 11]
 - Browser: [e.g. chrome, ]
 - PineSAM Version: [e.g. 1.12.15]
 - IronOS build/date: [e.g. 2.20.e13f118, 29-03-23]

**Comment by builder555** [comment]
@River-Mochi  can you give me the link to this firmware?
