### ISSUE TITLE
Graph:  watts range maximum at more common value

### ISSUE THREAD

**Issue by River-Mochi** [builder555/PineSAM#177]
Suggestion:  reduce  graph to  90w or 100w max  since most people will probably only  have max of 88w  with 24V DC barrel charger or  even using 28V USB-C PD3.1  charger they will still only maybe have about 87w-88w max on usage.  

- 90w or 100w  chart  gives more details on the lower range of graph which is most used area people encounter.
- graph will automatically  already grow taller if someone does do the rare  extreme testing over 100W (like me).  then graph display automically changes to include  110W  up for example.
- most of the chargers tested are all below the 70W range max on tests for myself and Ralim debugging I do, with some very few in the  85-90w category.   To get over 100W,  I have to do extreme things like  cup of water  which is not what normal people would do as it can harm the cartridge tip and get steam into the PCB also harming it.

**Comment by builder555** [comment]
Fixed in commit 692090f
