### ISSUE TITLE
haptic feedback for buttons while on a phone

### ISSUE THREAD

**Issue by River-Mochi** [builder555/PineSAM#179]
**Is your feature request related to a problem? Please describe.**

- Does anyone know how to add  haptic feedback for the  Preset buttons and the +/- buttons?
- It's sometimes hard to tell if a Preset button has been tapped on a phone without also looking closer; haptic on the buttons would help. 
- this would be for toggle buttons, preset buttons, +/- button. 

**Describe the solution you'd like**
add haptic feedback so  it works for iphone and android phones.
 see this article about haptic for Android:  https://developer.android.com/develop/ui/views/haptics/haptic-feedback

**alternatives**
is there something simple that could be activated on a phone so that anything you tap on in a browser gives feedback? I have not discovered how to do this as alternative.

I notice on my other phone apps they only have haptics for simple things like if I hit a Toggle button but it's not consistent,  in a single app I found only "some" toggles gave haptic and others did not as if it was different programmers that did the sections and they didn't do it consistently.

**Comment by builder555** [comment]
This [doesn't work](https://caniuse.com/?search=vibration) on iOS, so I have no way of testing it, if someone wants to implement it, they can create a PR.
