### ISSUE TITLE
Error handling message for windows Bluetooth

### ISSUE THREAD

**Issue by River-Mochi** [builder555/PineSAM#181]
**Is your feature request related to a problem? Please describe.**

If bluetooth services in Windows is toggled "off" or there is no working bluetooth on the PC, then PineSAM script  will exit because the Process IDs are killed but the message is not human friendly.

This image simulates  having bluetooth toggled **off** on windows:
![image](https://user-images.githubusercontent.com/97197236/232283297-ec3a17bb-7107-4e8e-a768-b2c3933a6e80.png)

**Describe the solution you'd like**
1.  Start script checks if  windows bluetooth is on or off.
2.  I made a script fix to do this but  needs more testing before I submit PR.

**Additional**
Example of  how the Setting should look in windows when it's ON:

![image](https://user-images.githubusercontent.com/97197236/232283725-d0681a4b-2d82-469a-9663-eb347a26e06d.png)

**Comment by River-Mochi** [comment]
I wrote a new windows script that test  if  Bluetooth Toggle is ON or OFF. 
I need to find testers to make sure it works on windows 10 also.   Zip is attached.

works on my  windows 11 everytime if I toggle off or on the buttons.  This section is part that checks the Bluetooth toggle:
```
# Check Bluetooth status
$bluetoothAdapter = Get-NetAdapter | Where-Object { $_.InterfaceDescription -like "*Bluetooth*" }
if ($bluetoothAdapter) {
    Write-Host "Good: Windows Bluetooth is Enabled." -ForegroundColor Green
} else {
    Write-Host "== WINDOWS BLUETOOTH IS DISABLED. TOGGLE IT ON, AND TRY AGAIN ==" -ForegroundColor Red
	exit 1
}

```

[start02.zip](https://github.com/builder555/PineSAM/files/11256065/start02.zip)

**Comment by River-Mochi** [comment]
This script has only been tested by  2x windows people so far.  I'm looking for more testers. So far it works.

1.  adds a few Error handlers
2. checks if bluetooth is on in windows settings - and tells user to Enable it.
3. checks if script is being executed from the pinesam folder otherwise path to main_server will fail - Tells user.
4. lets user know that Browser is starting. 
5. shows  PID  of both servers, and if one server fails, then Error message is printed to restart the terminal script.

### [start02.zip](https://github.com/builder555/PineSAM/files/11257033/start02.zip)

**Comment by builder555** [comment]
the starter script has been removed, so this issue is no longer relevant.
