### ISSUE TITLE
Settings Feature: Display Debug Data

### ISSUE THREAD

**Issue by River-Mochi** [builder555/PineSAM#39]
add a category called `Debug data`  to go before "Unused" which will show Tip R, Tip Res, and other information which is  not changeable by the user but very helpful in diagnosis and troubleshooting.  when people come into discord with a problem, we often ask them to give us the R-Tip and C-han right away since that is indicator of a possible Temperature sensor or Mosfet problem.  I believe that some of the Debug info is already transmitted.

**Comment by builder555** [comment]
Since voltage is already visible on the work view, this ticket could probably be a proper "debug view".

ACs:

- [ ] display all available "live" values (see #48)
- [ ] refresh values once every 5 seconds (to prevent bt/cpu stress)

**Comment by River-Mochi** [comment]
I am separating out  Debug information as most of  that is not some thing people need to see in the Work view.
Except for handle temperature  (which could also wait to go with graph view if there is no room for handle  temperature in the Work view screen?  depends on what you think for fitting it in. 

I'm opening a separate ticket for Debug info.
