### ISSUE TITLE
UI: scaling issue on iphone

### ISSUE THREAD

**Issue by River-Mochi** [builder555/PineSAM#40]
**To Reproduce**
Steps to reproduce the behaviour:
1. open in iphone, chrome browser, 1 letter will be cut off and not visible on the Left side of the  screen.

**Expected behaviour**
that there is a little white space on the left side of the screen before seeing words and that no letters are cut off.
Add a little white space to BOTH left and right side. although right side I can see all letters, the  blue boxes are still a little close to the right edge.  Left is problem, right side is just for better view but not a problem.  

**Actual behaviour**
1-2 letters are cut off on the left side, other big fonts like PineSAM are kissing the very edge.
even if I try to shift it over the display the  letter on left is cut off. 

**Screenshots**
![image](https://user-images.githubusercontent.com/97197236/220480934-6246d6c3-d896-4a6d-a150-220b027946c1.png)

**Specs:**
 - OS: iphone
 - Browser: chrome
 - **PineSAM** Version: 1.0.13 
 - IronOS build: beta 2.20.EB5D6EA  18-02-23

**Comment by River-b** [comment]
windows 11 chrome example 
Needs more white space border on the PC browser too.  if I make windows browser smaller to just 2 categories or 1 category view, then it also cuts off letters on the left side, and you can see right side is tight too, Show hints gets cut off and blue boxes are close to edge. 
![image](https://user-images.githubusercontent.com/97197236/220487795-f8f8f6f9-e488-4748-8ffb-9ecfb06ad9ac.png)

**Comment by builder555** [comment]
![iphone](https://user-images.githubusercontent.com/85308587/224585309-15908b8f-c99e-47f6-9b40-d29494049c1a.jpeg)
seems to have been fixed with the latest layout changes
