### ISSUE TITLE
Settings: Toggle button for Calibrate CJC has a different shape

### ISSUE THREAD

**Issue by River-Mochi** [builder555/PineSAM#53]
**To Reproduce**
open Chrome browser on windows PC

**Expected behaviour**
all toggle buttons are the same shape and size

**Actual behaviour**
Only the Calibrate toggle button is strange shape. it looks like instead of a white ball, it is vertical and partially cut off

**Screenshots**
![image](https://user-images.githubusercontent.com/97197236/221328379-f1870ca3-6a6b-42c3-96df-415890a67833.png)

**Comment by builder555** [comment]
ah, windows edge cases. i'll tweak the switches style a little

**Comment by River-Mochi** [comment]
fixed now  in version Source Code  PineSAM-1.5.7 I just tested.

![image](https://user-images.githubusercontent.com/97197236/224404345-eca0cda5-2ebc-43ab-92a5-bc1ab2da97fc.png)
