### ISSUE TITLE
Graph View

### ISSUE THREAD

**Issue by River-Mochi** [builder555/PineSAM#54]
**Is your feature request related to a problem? Please describe.**
### Graph features
- [x] Graph should contain data similar to other industry standard graphs used in the soldering field to examine behavior, slumping temperatures and watts. This information is useful to diagnose and inform decisions to adjust Temperature/Power or change Tips for improved PCB work.
- [x]  Screen 1 would be  60% Graph 40% Work View fuinctions (horizontal able if on phone). 
- [x] Screen 2, Full screen horizontal of Graph if on phone. perhaps if you double tap on the 60% graph it becomes full screen mode graph or select it from menu or toggle button.
- [x] Items needed in the graph: Left Y=Temp, Right Y=watts, bottom X = time/divisions (5s deired but if things are too slow increase to 10s).
- [x] Temp and watts line should be a different color (consider orange/red for temp, watts could possibly be the blue that is being used in setting boxes.
- [x] faint grid in the background.
- [ ] if the view is full  Graph chosen, then needs method on that screen to change temp & eventually record. recording is not part of this ticket.
- [ ] Integrating a Bar at the top showing the stage Pinecil is in would be helpful, see Tom's graph example showing if Pinecil is soldering/sleeping or some other stage (each has color code). bar should line up with the activity of the 2 lines in the chart.
- [ ] showing average temperature would be nice for period of soldering during the  set temperature  section.
- [ ] add a simple gray  horizontal line in the chart showing what the current Set temp is (see Tom's chart purple straight line).  this allows visual inspection of how off from Set point the temperature is fluctuating.
- [ ] add a line monitoring handle temperature and we might not need box with words "Handle 30C°" (see Tom's chart, green line).

### Why?
because people love graphs. it may also help to show how well Pinecil or the tip is performing if there are not huge slumps in temperature during soldering.
This would bring Pinecil to the next level as a FOSS tool.
![tiqdreng2](https://user-images.githubusercontent.com/97197236/222932985-f8677f58-6aec-4776-a332-3ceede85d5bf.png)

### Additional notes
request was made for recoding feature of the graph log to be able to play it back for analysis of soldering. that will be put into a separate ticket. for the short term,  suggest uses use one of the free screen recorders to record the screen with the graph activity for playback and examination.

### References
**Tom's App**: https://github.com/TomW1605/esphome_pinecilv2_ble
![Toms-graph2](https://user-images.githubusercontent.com/97197236/222932854-7abdec43-a3c7-4e2e-a711-d9e32925c064.png)

**Graphs help compare if you have good tips or if power of your station is keeping consistant temp on consecutive solder joints.**
example  chart can be used on 3 similar solder joints to compare. one that is more consistent and  doesnt slump down too much in temeperature moving from solder joint to next solder joint is better. 
![graph1](https://user-images.githubusercontent.com/97197236/222932885-adffb88e-8505-428d-b9a1-dab5e41e80d0.png)
![image](https://user-images.githubusercontent.com/97197236/222932450-60edcc88-5ecd-4305-8270-b857d115d6cb.png)

**Comment by River-Mochi** [comment]
sample Graph view
![Graph full view with record-play log](https://user-images.githubusercontent.com/97197236/222937953-1ccf8f8e-7761-4c0b-93af-d700c4fb358c.png)

**Comment by River-Mochi** [comment]
per 1.12.11 version.

-  thinner graph lines for Temperature and  Watts. right  now they are thick and not as smooth looking as other graphs.
- add veritical  lines for 1 sec/div  interval
- all graph lines should be "dashed"  and very  light gray  to not overwhelm the Temp/watts line colors
-  switch to FF00BF  for the  Temperature line as it compliments PineSAM colors and works
- X bar,  not in  bottom right   "Time 1s/div"

**Comment by builder555** [comment]
broke out some points into their own tickets, otherwise this issue is an entire project on its own.
