### ISSUE TITLE
UI: Color Current Temperature

### ISSUE THREAD

**Issue by River-Mochi** [builder555/PineSAM#57]
**Is your feature request related to a problem? Please describe.**
Current Temperature blends in with the rest of the screen although it is a moving live/hot temperature; it is currently Black

**Describe the solution you'd like**

- [ ]  1. If the number is under 40C , blue color  (for number only, Icon and °C could stay same black color)

 40-50C, green color
51-200C = yellow color
201C -375 C = Orange color
376- 450C = Red color

- [x]  2. DONE ~remove word  "temperature" and just have `CURRENT`  as the word "temperature"  is already indicated by `Icon ` and the `°C` . I like the smaller font kneel made "CURRENT" since it's a nice reference but doesn't need to pop out so much.~

**Comment by builder555** [comment]
(2) was closed in #48, @River-Mochi perhaps you can ~cross~ it out? (wrap text with `~`)
