### ISSUE TITLE
Clear Browser Data cache to prevent older version loading

### ISSUE THREAD

**Issue by River-Mochi** [builder555/PineSAM#58]
**Is your feature request related to a problem? Please describe.**
Problem is even if a new version is downloaded, the browsers on windows/iphone/android all load the old view of "settings.html"

- Might be user complaints that something is not working when it's just matter that they have old cache version still.
- Refreshing screen using refresh button does not "clear browser data"
- instructions to "clear browser data" differ for all platforms, I had to do it differentely in iphone/android/windows even though I was in Chrome on all three.

**Describe the solution you'd like**

1. Clickin refresh (blue icon also) "clears browser data" for PineSAM only
2. or  start script somehow refreshes cache for just PineSAM.

This will reduce user complaints that some feature in new version is not working or appearing.
I'm personally used to clearing it now as it has been required for each and every version I've downloaded before  any of the 3 platforms would display the newer "settings.html"

**Side Note:**
Refresh not working as expected.
1. Windows PC chrome browser, PineSAM refresh does not do a "reload" and Peak Watts does not clear. But hitting [F5] in browser works correctly to clear  "peak watts" number to 0.0W.
2.  Perhaps PineSAM refresh function could do  "F5"  because it does not appear to do that presently.
3.   iPhone, if I use PineSAM refresh icon, I still see the  old  "Peak watts" number. but if I select  3-dots in lower right and select "Reload"  from apple chrome settings, then Peak Watts is correctly cleared to 0.0W. 
4. Android -  also  PineSam refresh button does not clear Peal Watts to zero, but unfortunately I don't see this same "Reload" option anywhere like I see in iPhone Chrome.   Somehow  "Reload" is different than what happens  when we click  Blue refresh icon.  I have work around for iPhone and  Windows PC to  Refresh  and clear Peak Watts but not for android.

**Comment by builder555** [comment]
with new build system cache should not be an issue anymore
