### ISSUE TITLE
UI: dark reader mode, Category sections need more contrast color

### ISSUE THREAD

**Issue by River-Mochi** [builder555/PineSAM#59]
**Is your feature request related to a problem? Please describe.**
I personally use it on Light, but many other people use Dark Reader or phone app dark mode.
the Contrast for Section Categories and Sub-menu items is not enough to see clearly and determine section headers from the rest of the menu items.

**Describe the solution you'd like**
1. Contrast color that works for Dark Reader a little better.
2. Make the arrow down icon Bigger and more noticeable.

**Light normal mode works, arrow could be a little bigger:**
![image](https://user-images.githubusercontent.com/97197236/221692050-0731b8ab-506e-4999-a408-57a804335297.png)

**Dark Reader - browser extension. can't see difference in shade enough. arrow could be bigger icon:**
![image](https://user-images.githubusercontent.com/97197236/221692138-4112932c-8b67-48e4-8290-ac96165a4e2f.png)

**Comment by builder555** [comment]
can't really make changes to align with 3rd party style overlay - results are likely to be inconsistent. instead I'd need to make a proper dark theme and be able to switch between them.
