### ISSUE TITLE
Settings: Show Hints enabled by default for releases

### ISSUE THREAD

**Issue by River-Mochi** [builder555/PineSAM#64]
**Is your feature request related to a problem? Please describe.**
Recommend "show hints" is on by default in all releases so new people see not only the hints but what the "save to flash means"
They will then easily discover that clicking Show hints turns it all off later.

In readme instructions for Work View I could also add  something that "save to flash" can be left off while using Work view to solder to preserve  the limited flash cycles on all flash memory devices like Pinecil.

**Comment by builder555** [comment]
the changes that need to happen:

- [ ] change isHintVisible from `false` to `true` in the code
- [ ] store isHintVisible value in localStorage (same as presets)
- [ ] retrieve isHintVisible from localStorage on load
