### ISSUE TITLE
change icon to reflect current temperature

### ISSUE THREAD

**Issue by builder555** [builder555/PineSAM#66]
Change the thermometer icon in the main view based on current temperature:

- [ ] low-temperature icon for temperature <50C
- [ ] mid-temperature icon for 50C < temperature <=100C
- [ ] high-temperature icon when current temperature >100C

[low temp icon](https://fontawesome.com/v5/icons/thermometer-quarter?s=solid&f=classic)
[mid temp icon](https://fontawesome.com/v5/icons/thermometer-half?s=solid&f=classic)
[high temp icon](https://fontawesome.com/v5/icons/thermometer-three-quarters?s=solid&f=classic)

**Comment by River-Mochi** [comment]
Love the idea of  3 different Temp Icons that change depending on the range of temperatures.

Is it also possible for these icons to get a color? Physical shape change will help people with color  issues.
for people who can see color perhaps:

low temp icon  = make icon itself  yellow  (<50C)
mid temp icon  = orange   (50C <=200C)
high temp icon = Red  (> 201C)

- using alert colors  like typical icons use   caution = yellow, and stop or Red alert/danger  = red

**Comment by River-Mochi** [comment]
Could there be 4 icons to represent live temperature?
