### ISSUE TITLE
Release page enhancements

### ISSUE THREAD

**Issue by River-Mochi** [builder555/PineSAM#67]
**Is your feature request related to a problem? Please describe.**
**Releases page**

- [ ] 1. Add a named Release to be  called PineSAM.zip  if that is easier or pinesam1.3.1 (ver specific).
- [ ] 2. can leave the two "source code" zips if that is simpler. I don't think you can get rid of them, even IronOS has them but they automatically go to the bottom of the list over the named items. 
- [ ] 3. adding a Unique name, like PineSAM release will fix the problem with download badges not working as it will be counted by Github in the API page under the tag download_count.

reference: 
-https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
- https://github.com/marketplace/actions/auto-release
- https://github.com/marketplace/actions/automatic-releases
 
Example
![image](https://user-images.githubusercontent.com/97197236/221911332-4d4bb09e-b8ea-48e4-8211-515c1502ba70.png)

- [ ] 4. add a **Contributors** section to Releases page, similar to how the Icons show for [IronOS releases](https://github.com/Ralim/IronOS/releases)
- [ ] 5. add a **New contributors** section, this is for people who are making their first contribution to the repo, [ example here ](https://github.com/Ralim/IronOS/releases)

**Comment by builder555** [comment]
1. that is related to a new build process, i.e. packaging the application for release (e.g. using pyinstaller), i added #69 to address that

2, 3. Need to modify the release workflow for it, I need to research best/easiest way to implement it.

**Comment by River-Mochi** [comment]
> research best/easiest way to implement it

I did a view page code on Ralim's "release" page to see how he is adding contributors to display their Avator icons, but whole page is a little complex so I thought it was just better to link to you IronOS release page and you can view page code directly.

**Comment by builder555** [comment]
it's probably automatically generated by one of the workfows in .github/workflows

**Comment by River-Mochi** [comment]
This ticket  now  will also  fix the problem with Downloads badge not working.
once there is an archive there that is a binary zip package with a unique name  (not Source Code), then the API page for releases should start showing  download_count and that is what the badge reads to get count.

 it's probably ok to leave the 2 source code zips there, as many other repos just leave it there.  and have the new name package which will show up at the top.  most people  probably know from install instructions or  they are used to going in github and grabbing the thing with 'real name'  versus scary thing called 'source code.zip'

**Comment by builder555** [comment]
done
