### ISSUE TITLE
change folder name to PineSAM

### ISSUE THREAD

**Issue by River-Mochi** [builder555/PineSAM#72]
**Is your feature request related to a problem? Please describe.**

- Consider just naming the internal folder **PineSAM**
- Currently it looks like this:  `PineSAM1.3.1\PineSAM-**master**\backend`
- I like that the main folder name has the version number; for ease of usage, the internal folder of all downloads could simply be PineSAM or Pinesam.
- new structure would look like:  `PineSAM-1.3.1\PineSAM\backend`  or  `PineSAM-1.3.1\Pinesam\backend`

![image](https://user-images.githubusercontent.com/97197236/222266977-85bc13ef-808b-419a-82c1-ac2cdc1ca4a7.png)

**Comment by builder555** [comment]
I'm not sure what you mean, currently if you download from the release, it extracts into `PineSAM-1.3.1`
<img width="266" alt="image" src="https://user-images.githubusercontent.com/85308587/222268833-47eea7a0-2b09-4910-9457-94c683003c25.png">

**Comment by River-Mochi** [comment]
I mean the second level folder name and not the highest level.  see the screenshot image I included.
instead of **Pinesam-master**\backend  change it to just be pinesam\backend and remove the word "-master"
for what the user sees when they unxzip it.

technically they will see 3 folders/directories
PineSAM1.3.1\Pinesam\backend

**Comment by builder555** [comment]
that's what i'm referring to as well, when i unzip it, i only see `PineSAM-1.3.1\backend` i don't have the middle folder "pinesam-master" or anything else

**Comment by River-Mochi** [comment]
I see the Problem  the kink from the Windows Readme instructions gives a completely different file directory than the  Releases page.

![image](https://user-images.githubusercontent.com/97197236/222280687-e06ce9b8-41fd-4d94-b3b0-bb4e9e85cb21.png)

**Comment by builder555** [comment]
done
