### ISSUE TITLE
can not see Traffic in Insights

### ISSUE THREAD

**Issue by River-Mochi** [builder555/PineSAM#76]
**To Reproduce**
Steps to reproduce the behaviour:

Can not see Traffic under insights. It says it is visible to people using Github Free with a public repository.

https://docs.github.com/en/repositories/viewing-activity-and-data-for-your-repository/viewing-traffic-to-a-repository
https://docs.github.com/en/repositories/viewing-activity-and-data-for-your-repository/about-repository-graphs#traffic

I can see Insights > traffic on my own fork of Pinesam
![image](https://user-images.githubusercontent.com/97197236/222668740-c037aa09-7ab5-4813-8b2a-b1fe11690984.png)

**Comment by builder555** [comment]
The documentation states:
> Anyone with push access to a repository can view its traffic
