### ISSUE TITLE
UI Design: same blue for slider and boxes

### ISSUE THREAD

**Issue by River-Mochi** [builder555/PineSAM#78]
**Is your feature request related to a problem? Please describe.**

4 different blue colors currently. 
Different colors are good if they provide some good feedback or Alert, for example Fire-Orange temperature color if live temp is 320+ °C high.
in this case, just matter of no time yet to do; case of the clashing blues.

Per Builder555
- [ ] add CSS style to ensure the links (like the reload button and PineSAM) and sliders are the same colour as the boxes.
- [ ] Sliders and boxes, same color
- [ ] PineSAM and refresh same color.

![image](https://user-images.githubusercontent.com/97197236/222870245-4ada48db-da70-4180-8788-5fa6f87ec938.png)

**Comment by builder555** [comment]
went another direction, but now the colours are the same
