### ISSUE TITLE
Graph:  save and replay log of soldering session

### ISSUE THREAD

**Issue by River-Mochi** [builder555/PineSAM#80]
**Is your feature request related to a problem? Please describe.**

request was made for recording feature of the graph log to be able to play it back for analysis of soldering.

**Describe the solution you'd like**

- [ ] save log of whole session if that is easier (or record button).
- [ ] way to store logs 
- [ ] Graph full view has a media Play/Stop button to play back the log of Temperature/Watts graph.
- [ ] Forward and Reverse button.
- [ ] Log save and playback is dependent on the Graph work view ticket being complete.

**Additional context**
For the short term, suggest using one of the screen recorders to record the screen with the graph activity for playback and inspection.

**Comment by River-Mochi** [comment]
### Sample graph view with media play buttons
![Graph full view with record-play log](https://user-images.githubusercontent.com/97197236/222937415-72889c3f-2668-4511-ac60-0023e53f8102.png)

**Comment by builder555** [comment]
What would be the practical use case for it?

**Comment by builder555** [comment]
Given the lack of responses for this feature, I'm closing it as not planned. If there is a renewed interest, I'll re-open.
