### ISSUE TITLE
Integrate Check Authenticity inside PineSAM

### ISSUE THREAD

**Issue by River-Mochi** [builder555/PineSAM#83]
**Is your feature request related to a problem? Please describe.**

Per design group chat, Builder555 proposes to integrate the existing "checker for authenticity" into PineSAM that allows people to check their pinecil V2 authenticity more conveniently.

**Background:**
- reading and re-typing the long tiny ID and serial number from the small Pinecil screen and then transposing that into Authenticity checker is less convenient.
- not everyone knows about the checker unless they read wiki page or get a reminder in live chat channels that it exists.
- if it is a PineSAM feature, then people won't need an external reminder about the existence of the checker.
- integrating the checker will reduce the burden on the user to do extra steps; checker could be available in an app (PineSAM) that they use already for daily work.

**Proposed changes:**
- [ ]  Step 1, just having the ID and Serial number displayed somewhere on PineSAM for easy reading is a helpful first step. suggest it be in collapsible reference section with data that is not needed often. This allows people to make the numbers as big as they like for accessibility in the browser.
- [ ] BLE already sends ID, we need IronOS to send Serial number too (firmware support). refer to IronOS ticket https://github.com/Ralim/IronOS/issues/1609
- [ ]  Integrate "check authenticity" from inside PineSAM.

**Additional context**
1. Since the Authenticity checker  also is able to give Date of manufacture, then PineSAM could add to the collapsible reference section this and other details that people don't need to see all the time but might want to check sometimes without needing to go to authenticity checker website again.
2. how does the Serial number and ID get interpreted to give a date of manufacture?
3. people who complete authentication might get an icon like a blue checkmark or a star or something cute to mark to let them know they completed authentication (explore options/issues for people who own multiple pinecils).

**Comment by builder555** [comment]
The ID is sent over bluetooth, but the serial number is not, closing until it's implemented in firmware.
