### ISSUE TITLE
Notify if a new IronOS Release firmware is available

### ISSUE THREAD

**Issue by River-Mochi** [builder555/PineSAM#84]
**Is your feature request related to a problem? Please describe.**
**Background**

- It is a good idea to keep Pinecil updated.
- Pinecil owner's don't always know when there is a new release. some releases have important bug fixes and work arounds for compatibility with more chargers.
- Certain menu options that are taken for granted in new releases don't exist on older versions so there can be communication problems when troubleshooting.
- Some firmware updates resolve issues and prevent new ironOS tickets.
- This was never possible before when we did not have a BLE connection in pinecil.

**Describe the solution you'd like**

- [ ] send current installed firmware number over BLE to PineSAM (IronOS  support needed).
see ticket here: https://github.com/Ralim/IronOS/issues/1610
- [ ] Step 1, pinecil displays the installed firmware version in the collapsable references section (i.e. potentially same place as ID number, serial number) for things we don't need to see every day to work.
- [ ] Step 2. PineSAM checks the api Release page of IronOS to compare if the release number is higher than the current, and there is an icon that appears that lets the user know that an new stable update is available.
- [ ]  "update available" icon could be at the top of the screen, maybe glowing, a rainbow or happy face :)  jk.
Example icon could be the common "bell" that people are already used to in many apps and know it means there is an alert there.

![image](https://user-images.githubusercontent.com/97197236/224048443-096da677-1a55-4f43-843e-77438170a474.png)
![image](https://user-images.githubusercontent.com/97197236/224046357-07fd0e43-0179-407b-9d1f-62b15ab0c912.png)

![image](https://user-images.githubusercontent.com/97197236/224046670-32f18519-d72f-474c-89a1-788dc3bf4b1d.png)
![image](https://user-images.githubusercontent.com/97197236/224047892-3804ba34-65a7-4e4f-93a6-a5c7f6a76066.png)
![image](https://user-images.githubusercontent.com/97197236/224048195-96205160-c150-4039-93dd-3e8ae103e1a9.png)

**Comment by River-Mochi** [comment]
FYI  this just went up

Add FW version to BLE characteristic #2801
https://github.com/Ralim/IronOS/actions/runs/4497563158

**Comment by builder555** [comment]
closed in 095f7c0181e67ae865caa0dbf20b1b74d61420d5
