### ISSUE TITLE
Notify users if a new stable PineSAM release is available

### ISSUE THREAD

**Issue by River-Mochi** [builder555/PineSAM#85]
**Is your feature request related to a problem? Please describe.**
Notify users if a new stable PineSAM release is available so they don't have to keep checking in on the github weekly.

**Describe the solution you'd like**

- [ ] this ticket is dependent on first having a unique named artifact Release and not just "source code zips"
- [ ] Notify users if a new stable PineSAM release is available
- [ ] perhaps just check one time when the app is initially opened and compare it to the version already running.
- [ ] have a unique small icon at the top of the Work View that appears and stays there as long as they are on older version.  if they click on the icon, it displays "New PineSAM version available"
- [ ] also when users first start the script, the Browser has a Pop-up that alerts one time at the startm, in a friendly color, "New PineSAM update available, click on the Github Cat in the corner".

**Comment by River-Mochi** [comment]
For this,  was thinking only notify for major release change and not the little ones?  since the little ones seem to come several times per day.  it could get a little spammy.

**Comment by builder555** [comment]
i'm making it like this. very non-intrusive 
<img width="517" alt="image" src="https://user-images.githubusercontent.com/85308587/225157318-ef293795-fcb5-4019-883a-50c26775d59b.png">

**Comment by River-Mochi** [comment]
and then we just Click on the CAT  to go and get it?

**Comment by builder555** [comment]
you can click on the cat or on the "New version available" it's a link also
